### ISSUE TITLE
Refactor filename generation to support configuration & templating

### ISSUE THREAD

**Issue by xurizaemon** [integratedexperts/behat-steps#70]
It'd be nice to have control of the filename from `behat.yml` configuration, and interpolate configured variables (or template string) with values from the step at hand.

In this way people could perhaps generate more informative screenshot naming, eg that included the feature filename, step line, time (accounting for repeated line entries from Examples: tables), success/fail state and other useful context.

This would be a useful addition for things like #69.

**Comment by AlexSkrypnyk** [comment]
I think this meant to be for behat-screenshot project.

**Comment by xurizaemon** [comment]
Yes, along with #69 - apologies for the noise :D
